version: '2'
services:
  solarlog-exporter:
    build: .
    container_name: solarlog-exporter
    volumes:
      - ./tmp:/files
    depends_on:
      - influxdb
    env_file:
      - .env
    networks:
      - default

  influxdb:
    image: influxdb:1.8.4
    container_name: influxdb
    volumes:
      - influxdb-storage:/var/lib/influxdb
    env_file:
      - .env
    networks:
      - default

volumes:
  influxdb-storage:

networks:
  default:
    driver: bridge