version: '2.1'
services:
  influxdb:
    image: influxdb:1.8.4
    restart: always
    container_name: solarlog_influxdb
    environment:
      - INFLUXDB_DB=solarlog
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - solarlog

  solarlog-exporter:
    build:
      context: .
    restart: unless-stopped
    container_name: solarlog_exporter
    depends_on:
      influxdb:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_DB=solarlog
    networks:
      - solarlog

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - solarlog

networks:
  solarlog:
