version: '2'
services:
  solarlog-exporter:
    image: chrishrb/solarlog-exporter:v1.0
    container_name: solarlog-exporter
    volumes:
      - ./tmp:/files
    depends_on:
      - influxdb
    networks:
      - monitoring

  influxdb:
    # todo: latest is not supported yet
    image: influxdb:1.8.4
    container_name: influxdb
    volumes:
      - influxdb-storage:/var/lib/influxdb
    env_file:
      - .env
    networks:
      - monitoring

volumes:
  influxdb-storage:

networks:
  monitoring:
    external:
      name: monitoring