version: '2'
services:
  solarlog-exporter:
    image: chrishrb/solarlog-exporter:latest
    container_name: solarlog-exporter
    volumes:
      - ./tests/assets:/data
    environment:
      - INFLUXDB_DB=solarlog
    networks:
      - solarlog_monitoring

networks:
  monitoring:
    external:
      name: solarlog_monitoring