{
 "title": "SolarLog",
 "description": "Monitoring SolarLog Inverters",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "inverter",
    "label": "Wechselrichter",
    "query": "SHOW TAG VALUES  WITH KEY = \"inverter\" "
   },
   {
    "name": "system",
    "label": "Anlage",
    "query": "SHOW TAG VALUES  WITH KEY = \"system\" "
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pac",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Pac",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "solarlog_min",
     "select": [
      [
       { "params": [ "Pac" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" }
     ]
    },
    {
     "alias": "Ertrag",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "solarlog_min",
     "select": [
      [
       { "params": [ "Eday" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "Tag",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "solarlog_day",
     "select": [
      [
       { "params": [ "Pac" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "Monat",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solarlog_day",
     "select": [
      [
       { "params": [ "Pac" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "Jahr",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "solarlog_day",
     "select": [
      [
       { "params": [ "Pac" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "inverter" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "solarlog_day",
     "select": [
      [
       { "params": [ "Pac" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" },
       { "params": [ "Ertrag absolut AC [kWh]" ], "type": "alias" }
      ],
      [
       { "params": [ "Pdc" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" },
       { "params": [ "Ertrag absolut DC [kWh]" ], "type": "alias" }
      ],
      [
       { "params": [ "efficiency" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "WR Wirkungsgrad η [Tag]" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "system", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  { "title": "Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "PAC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$tag_inverter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "inverter" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "solarlog_min",
     "select": [
      [
       { "params": [ "Pac" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "inverter", "operator": "=~", "value": "/^$inverter$/" },
      { "condition": "AND", "key": "system", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_inverter",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "inverter" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "solarlog_min",
     "query": "SELECT mean(\"temperature\") FROM \"solarlog_day\" WHERE (\"inverter\" = 'WR 1') AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "inverter", "operator": "=~", "value": "/^$inverter$/" },
      { "condition": "AND", "key": "system", "operator": "=~", "value": "/^$system$/" }
     ]
    }
   ]
  }
 ]
}