name: Integration Test

# Run the nightly tests at at 8 AM UTC / 1 AM Pacific
on:
  schedule:
    #- cron: "0 8 * * *"
    - cron: "*/5 * * * *"

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      PROD_IMAGE: ghcr.io/chrishrb/solarlog-exporter:edge
      HUB_PULL_SECRET: NA
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to ghcr
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Create Network
        run: docker network create solarlog
      - name: Run integration tests
        run: /bin/sh integration-test.sh